#
###################################
# Site wide configuration
####################################
#
title:       "jacojang"
description: "jacojang의 일기장"
url:         "http://jacojang.github.io"

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false


sass:
    sass_dir: _sass

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jacojang 
  avatar: avatar.jpg
  job: "Software Engineer"
  bio: "AhnLab에서 서버개발자로 일하고 있는 Jacojang입니다."
  email: "jacojang@jacojang.com"
  disqus-shortname:
  twitter:
  facebook: "jacojang"
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "jacojang"
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "jacojang"
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
